api_id: 29630724
api_hash: '8e12421a95fd722246e0c0b194fd3e0c'
session_name: 'forwardgram'

output_channel_names:
  - 'Receiver'

input_channel_ids:
  - 1621425154  # Notorious Silva Signals
  - 2197451859  # ANNA TRADER - WITHOUT MARTINGALE
  - 2944619696  # Source two
  - 2054781860  # Igor Trader TM
  - 2052418759  # GAB TRADER - FREE OPERATIONS
  - 2074799242  # Lorenzo

output_channel_ids:
  - 3033183667
